### ISSUE TITLE
phoneNo in the example

### ISSUE THREAD

**Issue by mario-imperato** [rkritchat/jsonmask#2]
Apparently it fails to mask a number. Ss the matter of fact in your own example the 

`"phoneNo":123456789`

gets masked as 

"phoneNo":***45678*

I would simply suggest of masking numbers with numbers in that case.

**Comment by rkritchat** [comment]
Hello mario-imperato, 
 thanks for your suggestion but the purpose of jsonmask is for logging data only which is used in middleware for log the request / response json.
